version: "3"

# Manually create a network so we can use static IPs on the backend
networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"  # Use port 81 by default to not conflict with host
      - "443:443/tcp"
      # - "67:67/udp"  # Only required if you are using Pi-hole as your DHCP serve
    environment:
      # Change this to the IP of the RPi
      # ServerIP: '192.168.8.41'  # Deprecated, replaced by FTLCONF_LOCAL_IPV4 - Set to your server's LAN IP, used by web block modes and lighttpd bind address
      TZ: 'Asia/Jakarta'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      PIHOLE_DNS_: "10.0.1.2#5300"  # Forward DNS queries to dnscrypt
      # Enable DNS conditional forwarding for device name resolution
      # REV_SERVER: "true"
      # REV_SERVER_DOMAIN: "local"
      # REV_SERVER_TARGET: "192.168.8.1"
      # REV_SERVER_CIDR: "192.168.8.0/24"
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Join the internal network so Pi-hole can talk to dnscrypt
    networks:
      pihole_net:
        ipv4_address: 10.0.1.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
      # - NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
    depends_on:
      - dnscrypt  # Starts dnscrypt before Pi-hole

  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    # Restart on crashes and on reboots
    restart: unless-stopped
    expose:
      - "5300/udp"
      - "5300/tcp"
    environment:
      TZ: 'Asia/Jakarta'
    volumes:
      - './etc-dnscrypt-proxy:/config'
    # Attach cloudflared only to the private network
    networks:
      pihole_net:
        ipv4_address: 10.0.1.2
    dns:
      - 127.0.0.1
      - 1.1.1.1